pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh script: '''
                    echo "I am in build step"
                    chmod +x gradlew
                    ./gradlew build
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                    ./gradlew sonarqube \
                      -Dsonar.projectKey=tavisca-apaithane_CI-MarsRover \
                      -Dsonar.organization=tavisca-apaithane \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.login=8320360f4db132bfaa69cf8bccee04912e54aca9
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    docker build -t rmars -f .infra/docker/Dockerfile .
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    docker login -u abhi870 -p dockerhubpass docker.io
                    docker tag rmars abhi870/marsrover
                    docker push abhi870/marsrover
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}